/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "getDataService_constants.h"

namespace Test {

const dataConstants g_data_constants;

dataConstants::dataConstants() {
}

} // namespace

