/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef data_CONSTANTS_H
#define data_CONSTANTS_H

#include "getDataService_types.h"

namespace Test {

class dataConstants {
 public:
  dataConstants();

};

extern const dataConstants g_data_constants;

} // namespace

#endif
